import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Textbook sidebar with custom structure
  textbookSidebar: [
    {
      type: 'category',
      label: 'Front Matter',
      collapsed: false,
      items: [
        'front-matter/front-matter-introduction',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: Foundations',
      collapsed: false,
      items: [
        'module-1-foundations/week-01-physical-ai-overview',
        'module-1-foundations/week-02-ros2-fundamentals',
      ],
    },
    // You can add more modules here as you create more content
  ],

  // Keep the default tutorial sidebar for reference
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
};

export default sidebars;
